### ISSUE TITLE
liuqibase service errors

### ISSUE THREAD

**Issue by Floydian888** [CLARIN-PL/Inforex#68]
I ran `sudo ./docker-dev-up.sh` and all services started correctly. Then I stopped them with CTRL+C and started them once again with `sudo docker start id1 id2 ...`.

In the end got the following logs from this command `sudo docker logs inforex_liuqibase_1 --since 60m`:

```bash
Unexpected error running Liquibase: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Unexpected error running Liquibase: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Unexpected error running Liquibase: Duplicate entry 'aar' for key 'PRIMARY' [Failed SQL: INSERT INTO `lang` (`code`, `language`) VALUES
('aar', 'Afar'),
('abk', 'Abkhazian'),
('ace', 'Achinese'),
...
('zun', 'Zuni'),
('zxx', 'No linguistic content; Not applicable'),
('zza', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki')]
```
The liuqibase service exited with errors.

**Comment by mczuk** [comment]
Does it happen also when you run `./docker-dev-up.sh` ?

**Comment by mczuk** [comment]
This https://github.com/CLARIN-PL/Inforex/commit/93fe92eb0a5d940b28a35cead0be988b29cacbf7 should fix the issue.

**Comment by Floydian888** [comment]
Checked out https://github.com/CLARIN-PL/Inforex/commit/93fe92eb0a5d940b28a35cead0be988b29cacbf7, ran `sudo ./docker-dev-up.sh` and still getting this from `sudo docker logs inforex_liuqibase_1 --since 60m`:
```sh
Unexpected error running Liquibase: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

**Comment by mczuk** [comment]
Is `db_1` running? Can you connect to the database by phpMyAdmin (http://localhost:7080)?

**Comment by Floydian888** [comment]
Yes and yes.

**Comment by mczuk** [comment]
I have encountered a similar problem when building the images from a scratch. The problem is in synchronization between liquidate and db.  The ad hoc solution is to run again `./docker-dev-up.sh`. Please, let me know if this will fix the problem. I will have to figure out how to make liquibase to wait for db initialization when run for the first time.

**Comment by Floydian888** [comment]
I can tell that when I run `sudo ./docker-dev-up.sh` for the first time I get this in logs:
```
Unexpected error running Liquibase: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```
When I stop it with CTRL+C and run `sudo ./docker-dev-up.sh` the log looks like this:
```
Unexpected error running Liquibase: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Liquibase Update Successful
```

**Comment by mczuk** [comment]
I have added synchronization between db and liquibase containers. The change is on a feature branch https://github.com/CLARIN-PL/Inforex/tree/docker-dbsync. Please test it and let me know if this fixes the issue for you.

**Comment by Floydian888** [comment]
Now I get only this message in logs:
```
Liquibase Update Successful
```
although the `inforex_liuqibase` docker container exits.
Is this the expected behavior?

**Comment by mczuk** [comment]
Yes. It suppose to update the database schema on start and when done it stops.  

Now it looks ok.
